version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: homevault-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: homevault
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - homevault-network

  # HomeVault Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: homevault-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://admin:password@mongodb:27017/homevault?authSource=admin
      PORT: 5000
      CLIENT_ORIGIN: http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./backend:/app/backend
      - /app/backend/node_modules
    depends_on:
      - mongodb
    networks:
      - homevault-network
    command: npm run server

  # HomeVault Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: homevault-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000
      CHOKIDAR_USEPOLLING: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend
    networks:
      - homevault-network
    command: npm run client

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: homevault-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./uploads:/var/www/uploads:ro
    depends_on:
      - backend
      - frontend
    networks:
      - homevault-network
    profiles:
      - production

volumes:
  mongodb_data:
    driver: local

networks:
  homevault-network:
    driver: bridge 